# SPDX-FileCopyrightText: 2026 Green Pipe Partners, LLC
# SPDX-License-Identifier: MPL-2.0
moduleVersion=${moduleVersion}
sourceCommit=${sourceCommit}
sourceTag=${sourceTag}
sourceRepository=${sourceRepository}
licenseMode=${licenseMode}
