# SPDX-FileCopyrightText: 2026 Green Pipe Partners, LLC
# SPDX-License-Identifier: MPL-2.0
module.version=${moduleVersion}
source.commit=${sourceCommit}
source.tag=${sourceTag}
source.repository=${sourceRepository}
licenseMode=${licenseMode}
